apiVersion: v1
kind: Service
metadata:
  name: weather-prediction-server-app
spec:
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8083
  type: LoadBalancer
  selector:
    app: weather-prediction-server-app
