apiVersion: v1
kind: Deployment
metadata:
  name: weather-prediction-server-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-prediction-server-app
  template:
    metadata:
      labels:
        app: weather-prediction-server-app
    spec:
      containers:
        - name: weather-prediction-server-app
          image: weather-prediction-server-app
          ports:
            - containerPort: 8083
