apiVersion: v1
kind: Service
metadata:
  name: weather-prediction-server
spec:
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
  selector:
    app: weather-prediction-server
