apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-prediction-server-app
    k8s-app:  weather-prediction-server-app
  name: weather-prediction-server-app
spec:
  ports:
    - name: http
      port: 81
      protocol: TCP
      targetPort: 8081
  type: LoadBalancer
  selector:
    app: weather-prediction-server-app
