apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-prediction-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-prediction-server
  template:
    metadata:
      labels:
        app: weather-prediction-server
    spec:
      containers:
        - name: weather-prediction-server
          image: 609659644494.dkr.ecr.ap-south-1.amazonaws.com/weather-report-ecr:latest
          ports:
            - containerPort: 8080
