apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-prediction-server-app
    k8s-app:  weather-prediction-server-app
  name: weather-prediction-server-app
spec:
  ports:
    - name: http
      port: 8082
      protocol: TCP
      targetPort: 8083
  type: LoadBalancer
  selector:
    app.kubernetes.io/name:: weather-prediction-server-app
